# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qkW6GZL3v7KV8bm7PVT1jqpMY0n7JC4c
"""

import pandas as pd

cdr = pd.read_csv('data.csv', sep=',')

class tariff_11(object):
  def __init__(self):
    self.number = int(input())
    self.k_origin = 1.0
    self.k_dest = 1.0
    self.k_sms = 1.0
    self.free_sms = 5

print('Enter phone number')
user_1 = tariff_11()

check_origin = (cdr['call_duration'].loc[cdr['msisdn_origin'] == user_1.number].sum()) * user_1.k_origin
check_dest = (cdr['call_duration'].loc[cdr['msisdn_dest'] == user_1.number].sum()) * user_1.k_dest
check_sms = (cdr['sms_number'].loc[cdr['msisdn_origin'] == user_1.number].sum() - user_1.free_sms) * user_1.k_sms

check_total = check_origin + check_dest + check_sms
print('The total amount of payments according to the tariff = ', round(check_total, 2))

